DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS meal;
CREATE TABLE meal (
  id int(11) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  title varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO meal (title) VALUES ('Stuff'), ('Doodads');
